#!/usr/bin/env bash
# Assign domain and subdomain arguments to variables
DOMAIN="$1"
SUBDOMAIN="$2"

# Function to query DNS information for a subdomain
query_dns() {
    local subdomain="$1"
    local sub_domain
    local record_type
    local destination

    sub_domain=$(dig "$subdomain"."$DOMAIN" +noall +answer | awk -F'.' '{print $1}')
    record_type=$(dig "$subdomain"."$DOMAIN" +noall +answer | awk '{print $4}')
    destination=$(dig "$subdomain"."$DOMAIN" +noall +answer | awk '{print $5}')

    if [ -n "$sub_domain" ]; then
        echo "The subdomain $sub_domain is a $record_type record and points to $destination"
    else
        echo "The subdomain $subdomain does not exist"
    fi
}

# Perform DNS lookup for the domain and subdomain
if [ -n "$SUBDOMAIN" ]; then
    # Query information for the specified subdomain
    query_dns "$SUBDOMAIN"
else
    # Query information for the default subdomains
    query_dns "www"
    query_dns "lb-01"
    query_dns "web-01"
    query_dns "web-02"
fi

