#!/usr/bin/env bash

# Update package index and install Nginx
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

# Start nginx service
sudo service nginx start

# Allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index with "Hello World!"
echo -e "Hello World!" | sudo dd status=none of=/var/www/html/index.nginx-debian.html

# Restart Nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"

