#!/usr/bin/env bash
#install and configure HAproxy.
# Step 1: Install HAproxy
echo "Installing HAProxy..."
sudo apt-get update
sudo apt-get install -y haproxy

# Step 2: Configure HAproxy
echo "Configuring HAProxy..."
sudo echo "
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 52.3.253.170 check
    server web-02 18.210.17.65 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Step 3: Enable and restart HAproxy
echo "Enabling and restarting HAProxy..."
sudo systemctl enable haproxy
sudo systemctl restart haproxy

# Success message
echo "HAProxy is installed, configured, enabled, and running."

