#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed arc

# Script
current_date=$(date +"%Y-%m-%d")
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name ="$day-$month-$year.tar.gz"

sudo mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
