#!/bin/bash

for ((i = 1; i <= 20; i++)); do
    if [ $i -eq 4 ]; then
        echo "bad luck from China"
    elif [ $i -eq 9 ]; then
        echo "bad luck from Japan"
    elif [ $i -eq 17 ]; then
        echo "bad luck from Italy"
    else
    echo $i
done
